### ISSUE TITLE
Unable to rebuild fork

### ISSUE THREAD

**Issue by seanprpl** [jquense/react-big-calendar#1951]
Hi, I forked your repo in order to apply heavy customizations on it. But I can not use it in my main project now.

Steps taken.

1. run `npm i https://github.com/seanprpl/fkCalendar.git`
2. attempt to run my other project using your Calendar component.
3. Import fails
4. I review my fork of your repo and try to build it. I get this:

```
[!] Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
src/sass/styles.scss (1:0)
1: @import './variables';
   ^
2: @import './reset';
Error: Unexpected character '@' (Note that you need plugins to import files that are not JavaScript)
    at error (/home/sean/cp/flipkikCalendar/node_modules/rollup/dist/rollup.js:3866:30)
    at Module.error (/home/sean/cp/flipkikCalendar/node_modules/rollup/dist/rollup.js:14866:9)
    at tryParse (/home/sean/cp/flipkikCalendar/node_modules/rollup/dist/rollup.js:14784:16)
    at Module.setSource (/home/sean/cp/flipkikCalendar/node_modules/rollup/dist/rollup.js:15068:35)
    at /home/sean/cp/flipkikCalendar/node_modules/rollup/dist/rollup.js:18025:20
    at async Promise.all (index 7)
    at async Promise.all (index 14)
    at async Promise.all (index 2)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command
```

What steps do i need to take to compile the project?

**Comment by bartvanandel** [comment]
Looks like your webpack configuration may not be setup correctly to handle SCSS files (I'm assuming here that your own project, where you try to use the calendar, is using Webpack). You will need `sass-loader` for this, see https://webpack.js.org/loaders/sass-loader/

If this is not the issue, you will need to provide more information. What customizations are you doing? How do you build your custom version of the calendar component? Does this build succeed? Can you provide a minimal example to showcase the problem?
