### ISSUE TITLE
Nextjs build issue

### ISSUE THREAD

**Issue by maftimos-wq** [jquense/react-big-calendar#2244]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

No link

### Bug description

Trying to build my nextjs application and running into a build error.

I am on nextjs version 12.2.2.

I also tried lower version of react-big-calendar and react itself and nextjs itself. 

Generating static pages (0/60)
Error occurred prerendering page "/customer-service/application/daily-schedule". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading '0')
    at MonthView.renderHeaders (/Users/Documents//node_modules/react-big-calendar/lib/Month.js:302:22)
    at MonthView.render (/Users/Documents//node_modules/react-big-calendar/lib/Month.js:294:15)
    at d (/Users/Documents//node_modules/react-dom/cjs/react-dom-server.node.production.min.js:35:231)
    at bb (/Users/Documents//node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/Users/Documents/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/Users/Documents/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/Users/Documents/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/Users/Documents/node_modules/next/dist/server/render.js:756:46)
    at Object.defaultGetInitialProps (/Users/Documents/node_modules/next/dist/server/render.js:369:51)
    at Function.getInitialProps (/Users/Documents/.next/server/chunks/3105.js:387:20)

 const DnDCalendar = withDragAndDrop(Calendar)

and then using it in the following code 

<DnDCalendar
        views={views}
        date={date}
        view={view}
        events={events}
        getNow={getNow}
        localizer={localizer}
        onEventDrop={onEventChange}
        onEventResize={onEventChange}
        onSelectEvent={onSelectEvent}
        scrollToTime={scrollToTime}
        onView={onView}
        resizable={view !== 'month'}
        onNavigate={onNavigate}
        step={5}
        timeslots={12}
        resources={resources}
        resourceAccessor={(event: Event & IAdditionalEventProps) =>
          event.resource
        }
        resourceIdAccessor={(resource: any) => resource.id}
        resourceTitleAccessor={(resource: any) => resource.name || 'Resource'}
        dayLayoutAlgorithm="overlap"
        eventPropGetter={() => ({
          style: {
            backgroundColor: theme.palette.primary.main,
          },
        })}
        style={{ height: '120vh' }}
      />

const PROPS = {
    "views": {
        "month": true,
        "day": true
    },
    "date": "2022-07-26T15:08:04.029Z",
    "view": "month",
    "events": [],
    "localizer": {
        "formats": {
            "dateFormat": "dd",
            "dayFormat": "dd EEE",
            "weekdayFormat": "EEE",
            "timeGutterFormat": "t",
            "monthHeaderFormat": "MMMM yyyy",
            "dayHeaderFormat": "EEEE MMM dd",
            "agendaDateFormat": "EEE MMM dd",
            "agendaTimeFormat": "t"
        },
        "segmentOffset": 0
    },
    "scrollToTime": "2022-07-26T15:17:30.929Z",
    "resizable": false,
    "step": 5,
    "timeslots": 12,
    "resources": [],
    "dayLayoutAlgorithm": "overlap"
}

### Expected Behavior

Be able to build the app sucessfully.

### Actual Behavior

Breaking on build.

### react-big-calendar version

1.5.0

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by maftimos-wq** [comment]
I was able to figure this out. I cloned the repo and did some code tracing where the error came from.

If you are passing in views as week/day and wanting to disable month You must also pass the prop for defaultView={'week' || 'day'}

Otherwise when it first renders. defaultView is defaulted to 'month' which is not in your views and errors out.

I feel like this may be helpful to add to the documentation for future issues some may encounter with this.

**Comment by maftimos-wq** [comment]
This may have been a false positive. This error is still happening on build

**Comment by butermann** [comment]
Maybe try this?
```const PROPS = {
"views": ["week","day"],
"date": "2022-07-26T15:08:04.029Z",
"view": "week",
```

https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--cal-views

**Comment by maftimos-wq** [comment]
@butermann I tried doing that as well. 

I've come back with good news. After a lot of debugging. I found the issue.I have nailed the down to be a luxon and reactivity issue when the page first loads. DateTime.fromISO(date) returns an InvalidDate. Meaning on initial render, DateTime is not even defined.

As a short term fix, I added a isMounted condition with a 500ms timeout to render the component and all its logic correctly. The pain point seems to be that fromISO returns an invalid date for some reason.

With the isMounted condition I am able to build and render the page correctly.

I hope this helps anyone running into this issue in the future
