### ISSUE TITLE
[Question] Does this work with react router Dom and with nested components?

### ISSUE THREAD

**Issue by Henrycodeproj** [jquense/react-big-calendar#2339]
Hi, I've been trying to implement this calendar into my project but every time I click the agenda tab or just any days on the calendar I get an error that looks like this and I am not sure if there was an example or if this doesn't work with nested components. I am not sure if I am allowed to bring this up here, but much appreciated if I could get an answer on what's happening. Thanks again if I could get help, if not I can take this down if this isn't allowed.
        
```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
        
Uncaught TypeError: Cannot read properties of null (reading 'useMemo')
at useMemo (react.development.js:1650:1)
at TimeGutter (react-big-calendar.esm.js:3603:1)
at renderWithHooks (react-dom.development.js:16141:1)
at mountIndeterminateComponent (react-dom.development.js:20838:1)
at beginWork (react-dom.development.js:22342:1)
at HTMLUnknownElement.callCallback (react-dom.development.js:4157:1)
at Object.invokeGuardedCallbackDev (react-dom.development.js:4206:1)
at invokeGuardedCallback (react-dom.development.js:4270:1)
at beginWork$1 (react-dom.development.js:27243:1)
at performUnitOfWork (react-dom.development.js:26392:1)
```

I am importing calendar component directly and followed the get started template for localizer for date-fns. I then call it in a parent component like this.
```

<parent component>
   <calendar/>
</parent component>
```

**Comment by cutterbl** [comment]
If you are filing a bug, please clone the [Codesandbox](https://codesandbox.io/s/react-big-calendar-example-v9wdyd?file=/src/index.js) and create an example, so that we can troubleshoot your issue.
